import { test, expect } from '@playwright/test';
import { createProgress } from '../../app/utils/progress.js';
import { addCopies } from '../../app/utils/inventory.js';
const key = 'dragon-vault-boxes-v4';
const saved = (page) => page.evaluate((k) => JSON.parse(localStorage.getItem(k)), key);
async function capture(page, name) {
  await expect(page.locator('main h1')).toBeVisible();
  await expect(page.locator('#toast.show')).toHaveCount(0);
  for (const [device, width, height] of [['desktop', 1440, 1000], ['mobile', 390, 844]]) {
    await page.setViewportSize({ width, height });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: `.impeccable/review/${name}-${device}.png`, fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
}
test('crear formato, permitir y limitar, importar expansión, publicar, obtener y armar mazos aislados', async ({ page }) => {
  test.setTimeout(90000);
  const id = '36996508', s = createProgress();
  addCopies(s, id, 3, { source: 'LOB', sourceName: 'Clásicas', rarity: 'Common' });
  await page.goto('/formatos');
  await page.evaluate(({ key, s }) => localStorage.setItem(key, JSON.stringify(s)), { key, s });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Mazos de inicio', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Sobres', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Crear formato', exact: true }).click();
  await page.getByLabel('Nombre de la nueva lista', { exact: true }).fill('Speed entre amigos');
  await page.getByRole('button', { name: 'Guardar nuevo formato', exact: true }).click();
  const formatId = (await saved(page)).formats[1].id;
  await page.getByRole('searchbox', { name: 'Buscar cartas para la lista', exact: true }).fill(id);
  const limits = page.getByRole('group', { name: 'Límite de Mago Oscuro', exact: true });
  await expect(limits.getByRole('button', { name: 'No permitida', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await limits.getByRole('button', { name: '1 copia', exact: true }).click();
  await page.getByText('Agregar una expansión completa a la lista', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Expansión a incorporar', exact: true }).selectOption('classic:LOB');
  await page.getByRole('button', { name: 'Agregar cartas permitidas', exact: true }).click();
  expect((await saved(page)).formats[1].limits[id]).toBe(1);
  await capture(page, 'formats-rules');
  await page.goto('/mazos');
  await page.getByRole('combobox', { name: 'Formato de los mazos', exact: true }).selectOption(formatId);
  await page.getByRole('button', { name: /Crear un mazo/ }).click();
  await expect(page.getByRole('button', { name: 'Agregar Mago Oscuro', exact: true })).toHaveCount(0);
  await page.goto('/especiales');
  await page.getByRole('combobox', { name: 'Formato del producto', exact: true }).selectOption(formatId);
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Sobre del nuevo formato');
  await page.getByRole('combobox', { name: 'Cartas por sobre', exact: true }).selectOption('1');
  await page.getByRole('button', { name: 'Agregar cartas del catálogo', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Buscar cartas', exact: true }).fill(id);
  await page.getByRole('button', { name: 'A expansión', exact: true }).click();
  await page.getByRole('button', { name: 'Ir al editor de expansiones', exact: true }).click();
  await page.getByRole('button', { name: 'Crear y publicar expansión', exact: true }).click();
  let state = await saved(page);
  expect(state.economy.customPacks[0].formatId).toBe(formatId);
  expect(state.formats[1].limits[id]).toBe(1);
  await page.goto('/formatos?formato=' + formatId);
  await expect(page.getByRole('button', { name: /Sobre del nuevo formato/ })).toBeVisible();
  await expect(page.getByRole('button', { name: /La leyenda del Dragón Blanco/ })).toHaveCount(0);
  await capture(page, 'formats-products');
  await page.getByRole('button', { name: /Sobre del nuevo formato/ }).click();
  await page.getByRole('button', { name: /Abrir.*sobre/ }).click();
  state = await saved(page);
  expect(state.owned[id]).toBe(4);
  expect(state.inventory[id].find((l) => l.formatId === formatId).quantity).toBe(1);
  await page.goto('/coleccion');
  await page.getByRole('combobox', { name: 'Formato de la colección', exact: true }).selectOption(formatId);
  await page.getByRole('searchbox', { name: 'Buscar cartas', exact: true }).fill(id);
  await expect(page.getByRole('button', { name: 'Ver Mago Oscuro', exact: true }).locator('.copies')).toHaveText('1×');
  await capture(page, 'formats-collection');
  await page.goto('/mazos');
  await page.getByRole('combobox', { name: 'Formato de los mazos', exact: true }).selectOption(formatId);
  await page.getByRole('button', { name: 'Agregar Mago Oscuro', exact: true }).click();
  await expect(page.locator('.deck-stock').first()).toContainText('Tenés 1');
  await expect(page.getByRole('button', { name: 'Agregar Mago Oscuro', exact: true })).toBeDisabled();
  await capture(page, 'formats-decks');
  await page.reload();
  await page.getByRole('combobox', { name: 'Formato de los mazos', exact: true }).selectOption(formatId);
  await expect(page.getByRole('button', { name: 'Quitar Mago Oscuro', exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Formato de los mazos', exact: true }).selectOption('official');
  await expect(page.getByRole('button', { name: 'Quitar Mago Oscuro', exact: true })).toHaveCount(0);
});

test('crear producto en otro formato confirma reemplazo y cancelar conserva el borrador', async ({ page }) => {
  const s = createProgress();
  s.formats.push({ id: 'custom-format', name: 'Mi formato', limits: {} });
  await page.goto('/especiales');
  await page.evaluate(({ key, s }) => localStorage.setItem(key, JSON.stringify(s)), { key, s });
  await page.reload();
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Borrador de Oficial');
  await page.getByRole('link', { name: 'Formatos', exact: true }).click();
  await page.getByRole('combobox', { name: 'Formato', exact: true }).selectOption('custom-format');
  await page.getByRole('button', { name: 'Crear producto propio', exact: true }).click();
  await page.locator('dialog[open]').getByRole('button', { name: 'Cancelar', exact: true }).click();
  await page.getByRole('link', { name: 'Expansiones', exact: true }).click();
  await page.getByRole('link', { name: 'Mis creaciones', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'Nombre', exact: true })).toHaveValue('Borrador de Oficial');
  await expect(page.getByRole('combobox', { name: 'Formato del producto', exact: true })).toHaveValue('official');
  await page.getByRole('link', { name: 'Formatos', exact: true }).click();
  await page.getByRole('button', { name: 'Crear producto propio', exact: true }).click();
  await page.locator('dialog[open]').getByRole('button', { name: 'Reemplazar borrador', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'Nombre', exact: true })).toHaveValue('');
  await expect(page.getByRole('combobox', { name: 'Formato del producto', exact: true })).toHaveValue('custom-format');
});
