import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import { database, schema } from '../../server/lib/database.mjs';
import { hashPassword } from '../../server/lib/auth.mjs';
import { createProgress } from '../../app/utils/progress.js';
import { personalState } from '../../server/lib/vault.mjs';
import { addCopies } from '../../app/utils/inventory.js';

const suffix = randomUUID().slice(0, 8), pass = 'Coleccion-navegador-2026';
const admin = { id: randomUUID(), username: `admin-${suffix}` }, player = { id: randomUUID(), username: `coleccion-${suffix}` };
test.beforeAll(async () => {
  expect(new URL(process.env.DATABASE_URL).pathname).toMatch(/_test$/);
  await database().query(schema);
  const hash = await hashPassword(pass);
  for (const [u, role] of [[admin, 'admin'], [player, 'player']]) await database().query('INSERT INTO vault_users(id,username,password_hash,role) VALUES($1,$2,$3,$4)', [u.id, u.username, hash, role]);
  const state = createProgress();
  for (const id of ['89631139', '36996508', '53129443']) addCopies(state, id, 3, { source: 'admin', sourceName: 'Entrega administrativa', rarity: 'Rare', formatId: 'official' });
  await database().query('INSERT INTO vault_progress(user_id,state) VALUES($1,$2)', [player.id, personalState(state)]);
  await mkdir('.impeccable/review/admin-collection', { recursive: true });
});
test.afterAll(async () => { await database().query('DELETE FROM vault_users WHERE id=ANY($1::uuid[])', [[admin.id, player.id]]); await database().end(); });
test('administrar una colección ajena en escritorio y móvil', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/login');
  await page.getByLabel('Usuario', { exact: true }).fill(admin.username);
  await page.getByLabel('Contraseña', { exact: true }).fill(pass);
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await expect(page).toHaveURL(/\/formatos$/);
  await page.goto('/usuarios');
  await page.getByRole('button', { name: `Administrar colección de ${player.username}`, exact: true }).click();
  await expect(page.getByRole('heading', { name: `Colección de ${player.username}`, exact: true })).toBeVisible();
  await expect(page.locator('.admin-inventory > li')).toHaveCount(3);
  await page.getByLabel('Buscar carta para entregar', { exact: true }).fill('Blue-Eyes White Dragon');
  await page.locator('.admin-card-results button').filter({ has: page.getByText('Blue-Eyes White Dragon', { exact: true }) }).click();
  await page.getByLabel('Rareza de entrega').selectOption('Ultra Rare');
  await page.getByLabel('Copias a entregar').fill('2');
  await page.getByRole('button', { name: 'Entregar cartas', exact: true }).click();
  await expect(page.locator('.admin-collection').getByRole('status').filter({ hasText: 'entregadas' })).toBeVisible();
  const card = page.locator('.admin-inventory > li').filter({ hasText: 'Dragón Blanco de Ojos Azules' });
  await expect(card.locator('.admin-lot')).toHaveCount(2);
  await page.screenshot({ path: '.impeccable/review/admin-collection/desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '.impeccable/review/admin-collection/mobile.png', fullPage: true });
  const rare = card.locator('.admin-lot').filter({ has: page.getByText('Rara', { exact: true }) });
  await rare.getByRole('spinbutton').fill('1');
  await rare.getByRole('button', { name: 'Guardar cantidad' }).click();
  await page.getByRole('button', { name: 'Confirmar reducción', exact: true }).click();
  await expect(rare.getByRole('spinbutton')).toHaveValue('1');
  await page.getByRole('button', { name: 'Actualizar colección', exact: true }).click();
  await expect(rare.getByRole('spinbutton')).toHaveValue('1');
  await page.getByRole('button', { name: `Vaciar colección de ${player.username}`, exact: true }).click();
  await expect(page.getByRole('button', { name: 'Eliminar todas las cartas' })).toBeDisabled();
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await expect(page.locator('.admin-inventory > li')).toHaveCount(3);
  await page.getByRole('button', { name: `Vaciar colección de ${player.username}`, exact: true }).click();
  await page.getByLabel(`Escribí ${player.username} para confirmar`).fill(player.username);
  await page.getByRole('button', { name: 'Eliminar todas las cartas' }).click();
  await expect(page.getByText('Esta cuenta todavía no tiene cartas. Podés entregarle las primeras arriba.')).toBeVisible();
  await page.getByRole('button', { name: 'Volver a usuarios', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Usuarios', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
