import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { database, schema } from '../../server/lib/database.mjs';
import { hashPassword } from '../../server/lib/auth.mjs';
import { mkdir } from 'node:fs/promises';
import { createProgress } from '../../app/utils/progress.js';

const suffix=randomUUID().slice(0,8), pass='Navegador-seguro-2026';
const admin={id:randomUUID(),username:'webadmin-'+suffix},player={id:randomUUID(),username:'webplayer-'+suffix};
test.beforeAll(async()=>{
  expect(new URL(process.env.DATABASE_URL).pathname).toMatch(/_test$/);
  await database().query(schema); const hash=await hashPassword(pass);
  for(const [user,role] of [[admin,'admin'],[player,'player']])await database().query('INSERT INTO vault_users(id,username,password_hash,role) VALUES($1,$2,$3,$4)',[user.id,user.username,hash,role]);
  await mkdir('.data/auth-review',{recursive:true});
});
test.afterAll(async()=>{await database().query('DELETE FROM vault_users WHERE id=ANY($1::uuid[])',[[admin.id,player.id]]);await database().end();});
async function login(page,user){await page.goto('/login');await page.getByLabel('Usuario',{exact:true}).fill(user.username);await page.getByLabel('Contraseña',{exact:true}).fill(pass);await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/\/formatos$/);}
test('acceso, administración, importación y progreso compartido en escritorio y móvil',async({page,browser})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('/coleccion');await expect(page).toHaveURL(/\/login$/);
  await page.screenshot({path:'.data/auth-review/login-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.data/auth-review/login-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1440,height:1000});await login(page,admin);
  const old = createProgress(); old.coins = 1777;
  await page.evaluate(state=>localStorage.setItem('dragon-vault-boxes-v4',JSON.stringify(state)),old);
  await page.getByRole('button',{name:'Guardar / cargar',exact:true}).click();
  await page.getByRole('button',{name:'Importar progreso de este navegador',exact:true}).click();
  await page.getByRole('button',{name:'Importar progreso',exact:true}).click();
  await expect(page.locator('#wallet')).toContainText('1.777');
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('dragon-vault-boxes-v4')).coins)).toBe(1777);
  old.coins=1888;
  await page.getByRole('button',{name:'Guardar / cargar',exact:true}).click();
  await page.locator('input[type="file"]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(old))});
  await page.getByRole('button',{name:'Importar mi progreso y configuración compartida',exact:true}).click();
  await page.getByRole('button',{name:'Importar copia',exact:true}).click();
  await expect(page.locator('#wallet')).toContainText('1.888');
  await page.getByRole('link',{name:'Usuarios',exact:true}).click();await expect(page.getByRole('heading',{name:'Usuarios',exact:true})).toBeVisible();
  await page.screenshot({path:'.data/auth-review/users-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.data/auth-review/users-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1440,height:1000});
  const newName='created-ui-'+suffix;
  await page.getByLabel('Usuario',{exact:true}).fill(newName);await page.getByLabel('Contraseña inicial').fill(pass);
  await page.getByRole('button',{name:'Crear cuenta',exact:true}).click();
  await expect(page.getByText(`Cuenta ${newName} creada.`,{exact:true})).toBeVisible();
  await database().query('DELETE FROM vault_users WHERE username=$1',[newName]);
  const context=await browser.newContext();const other=await context.newPage();other.on('pageerror',error=>errors.push(error.message));await login(other,player);
  await expect(other.getByRole('link',{name:'Usuarios',exact:true})).toHaveCount(0);
  await other.goto('/usuarios');await expect(other).toHaveURL(/\/formatos$/);
  await other.goto('/tienda');await expect(other.getByRole('button',{name:'Editar tienda'})).toHaveCount(0);
  await other.goto('/mazos');await other.getByRole('button',{name:'Crear un mazo'}).click();await expect(other.getByLabel('Elegir mazo').locator('option')).toHaveCount(1);
  await other.reload();await expect(other.getByLabel('Elegir mazo').locator('option')).toContainText('Mi mazo');
  await other.goto('/banlists');await expect(other.getByText('Las reglas las administra el creador')).toBeVisible();
  await other.getByRole('button',{name:/Salir/}).click();await expect(other).toHaveURL(/\/login$/);
  await context.close();
  expect(errors).toEqual([]);
});
