import test from 'node:test';
import assert from 'node:assert/strict';
import { createProgress, validate, clone } from '../app/utils/progress.js';
import { addCopies, lotKey, identifyCopies } from '../app/utils/inventory.js';
import { formatOwned, ownedInFormat, allowCards, formatLimit } from '../app/utils/formats.js';
import { changeDeck, Economy, grantStarter } from '../app/utils/actions.js';
import { saveExpansion } from '../app/utils/expansions.js';
import { cards } from '../app/utils/catalog.js';
import { cardLimit, banlistConflicts } from '../app/utils/banlists.js';
const id = '36996508';
function state() {
  const s = createProgress();
  s.formats.push({ id: 'speed', name: 'Speed entre amigos', limits: {} });
  return s;
}
const lot = (formatId, quantity = 4) => ({ source: 'custom-a', sourceName: 'Prueba', rarity: 'Common', formatId, quantity });
test('migra versión 5 a Oficial sin alterar productos, saldo, colección ni mazos; rechaza referencias rotas', () => {
  const s = createProgress();
  addCopies(s, id, 3, { source: 'shop', sourceName: 'Tienda', rarity: 'Common' });
  s.decks.push({ id: 'old', name: 'Anterior', cards: { [id]: 2 } });
  const old = clone(s); old.version = 5; delete old.formats;
  const next = validate(old);
  assert.equal(next.version, 7);
  for (const key of ['owned', 'inventory', 'decks', 'economy', 'coins', 'boxes']) assert.deepEqual(next[key], s[key]);
  assert.equal(formatLimit(next, 'official', id), 3);
  const corrupt = clone(next); corrupt.decks[0].formatId = 'missing';
  assert.throws(() => validate(clone(corrupt)), /no existe/);
  delete corrupt.formats;
  assert.throws(() => validate(corrupt), /formatos/);
});
test('whitelist y banlist aplican el menor límite, nunca prestan copias entre formatos', () => {
  const s = state();
  addCopies(s, id, 3, lot('official'));
  s.decks.push({ id: 'speed-deck', formatId: 'speed', name: 'Speed', cards: {} });
  assert.throws(() => changeDeck(s, 'speed-deck', id, 1), /permitidas/);
  allowCards(s, 'speed', [id]);
  assert.throws(() => changeDeck(s, 'speed-deck', id, 1), /copias obtenidas/);
  addCopies(s, id, 2, lot('speed'));
  changeDeck(s, 'speed-deck', id, 1);
  changeDeck(s, 'speed-deck', id, 1);
  assert.equal(s.owned[id], 5);
  assert.equal(ownedInFormat(s, id, 'official'), 3);
  assert.deepEqual(formatOwned(s, 'speed'), { [id]: 2 });
  s.formats[1].limits[id] = 1;
  s.banlists.push({ id: 'rules', name: 'Más restricciones', limits: { [id]: 3 } });
  s.decks[0].banlistId = 'rules';
  assert.equal(cardLimit(s, s.decks[0], id), 1);
  assert.equal(banlistConflicts(s, s.decks[0]).length, 1);
  assert.deepEqual(validate(clone(s)), s);
  s.banlists[0].limits[id] = 0;
  assert.equal(cardLimit(s, s.decks[0], id), 0);
  allowCards(s, 'speed', [id]);
  assert.equal(s.formats[1].limits[id], 1);
  s.decks[0].cards[id] = 3;
  assert.throws(() => validate(clone(s)), /copias obtenidas/);
});
test('publicar, abrir y duplicar conserva origen; los borradores no habilitan cartas', () => {
  const s = state();
  const p = { id: 'custom-a', name: 'Un sobre', formatId: 'speed', cost: 5, size: 1, status: 'draft', entries: [{ id, copies: 5, remaining: 5, rarity: 'Common' }] };
  saveExpansion(s, clone(p));
  assert.equal(formatLimit(s, 'speed', id), 0);
  p.status = 'published'; saveExpansion(s, clone(p));
  assert.equal(formatLimit(s, 'speed', id), 3);
  Economy.draw(s, cards, p.id, () => 0);
  assert.equal(ownedInFormat(s, id, 'speed'), 1);
  assert.equal(ownedInFormat(s, id, 'official'), 0);
  assert.throws(() => saveExpansion(s, { ...clone(p), formatId: 'official' }), /Duplicá/);
  saveExpansion(s, { ...clone(p), id: 'custom-b', formatId: 'official' });
  assert.equal(s.economy.customPacks[0].entries[0].remaining, 4);
  s.economy.customPacks = [];
  assert.equal(ownedInFormat(validate(clone(s)), id, 'speed'), 1);
});
test('ventas y excedentes protegen por formato, no por el total global', () => {
  const s = state(); allowCards(s, 'speed', [id]);
  addCopies(s, id, 4, lot('official')); addCopies(s, id, 3, lot('speed'));
  s.decks = [{ id: 's', formatId: 'speed', name: 'S', cards: { [id]: 3 } }, { id: 'o', name: 'O', cards: { [id]: 2 } }];
  assert.equal(Economy.protectedCopies(s, id), 5);
  assert.throws(() => Economy.quoteSale(s, cards, [{ id, lot: lotKey(lot('speed')), quantity: 1 }]), /mazo/);
  const extra = Economy.excess(s);
  assert.equal(extra.length, 1); assert.equal(extra[0].quantity, 1);
  Economy.sell(s, cards, extra);
  assert.equal(ownedInFormat(s, id, 'official'), 3);
  assert.equal(ownedInFormat(s, id, 'speed'), 3);
  assert.deepEqual(validate(clone(s)), s);
});
test('la identificación histórica no cambia formato y los mazos comprados conservan su formato', () => {
  const s = state();
  addCopies(s, id, 1, { source: 'legacy', sourceName: 'Anterior', rarity: null });
  assert.throws(() => identifyCopies(s, id, 1, lot('speed')), /no cambia el formato/);
  const entries = cards.filter((c) => c.type === 'Normal Monster').slice(0, 14).map((c) => ({ id: String(c.id), copies: 3, remaining: 3, rarity: 'Common' }));
  saveExpansion(s, { id: 'custom-starter', name: 'Inicio Speed', formatId: 'speed', kind: 'starter', status: 'published', cost: 10, size: 1, entries });
  grantStarter(s, 'custom-starter', true, 'new');
  assert.equal(s.decks[0].formatId, 'speed');
  assert.equal(ownedInFormat(s, entries[0].id, 'speed'), 3);
  assert.deepEqual(validate(clone(s)), s);
});
